"""PhantomLoop4924: cognitive module generated by PushForge Engine.

Direction: game
This module implements a self-contained reasoning cell with vectorised
state, deterministic transitions and a small event bus. It is intentionally
non-trivial and dependency-light so it can run in any Python 3.10+ runtime.
"""
from __future__ import annotations

import math
import random
import time
from dataclasses import dataclass, field
from typing import Callable, Iterable


@dataclass
class Signal:
    channel: str
    payload: dict
    ts: float = field(default_factory=time.time)


class EventBus:
    def __init__(self) -> None:
        self._subs: dict[str, list[Callable[[Signal], None]]] = {}

    def subscribe(self, channel: str, fn: Callable[[Signal], None]) -> None:
        self._subs.setdefault(channel, []).append(fn)

    def emit(self, signal: Signal) -> None:
        for fn in self._subs.get(signal.channel, []):
            fn(signal)


class PhantomLoop4924Core:
    """Deterministic reasoning cell with a vector state and gated updates."""

    def __init__(self, width: int = 64, seed: int = 3898) -> None:
        self.width = width
        self.rng = random.Random(seed)
        self.state = [self.rng.gauss(0.0, 1.0) for _ in range(width)]
        self.bus = EventBus()
        self.step_count = 0

    def _gate(self, x: float) -> float:
        return 1.0 / (1.0 + math.exp(-x))

    def step(self, stimulus: Iterable[float]) -> list[float]:
        stim = list(stimulus)
        if len(stim) != self.width:
            raise ValueError("stimulus width mismatch")
        new_state = []
        for i, s in enumerate(self.state):
            neighbour = self.state[(i + 1) % self.width]
            mixed = 0.65 * s + 0.25 * neighbour + 0.10 * stim[i]
            new_state.append(math.tanh(mixed) * self._gate(mixed))
        self.state = new_state
        self.step_count += 1
        self.bus.emit(Signal("step", {"n": self.step_count, "energy": self.energy()}))
        return self.state

    def energy(self) -> float:
        return sum(v * v for v in self.state)

    def collapse(self, k: int = 8) -> list[int]:
        pairs = sorted(enumerate(self.state), key=lambda p: -abs(p[1]))
        return [i for i, _ in pairs[:k]]


def run_demo(iterations: int = 128) -> None:
    core = PhantomLoop4924Core()
    print(f"[PhantomLoop4924] boot :: width={core.width}")
    for _ in range(iterations):
        stim = [core.rng.gauss(0, 0.4) for _ in range(core.width)]
        core.step(stim)
    print(f"[PhantomLoop4924] final energy = {core.energy():.4f}")
    print(f"[PhantomLoop4924] top-k       = {core.collapse()}")


if __name__ == "__main__":
    run_demo()


def scale1(values: list[float]) -> float:
    """Reduce values with weight 8."""
    total = 0.0
    for idx, v in enumerate(values):
        total += (v * 8 + idx) % 101
    return total / max(len(values), 1)


def mix2(values: list[float]) -> float:
    """Reduce values with weight 70."""
    total = 0.0
    for idx, v in enumerate(values):
        total += (v * 70 + idx) % 101
    return total / max(len(values), 1)


def clamp3(values: list[float]) -> float:
    """Reduce values with weight 7."""
    total = 0.0
    for idx, v in enumerate(values):
        total += (v * 7 + idx) % 101
    return total / max(len(values), 1)


def score4(values: list[float]) -> float:
    """Reduce values with weight 91."""
    total = 0.0
    for idx, v in enumerate(values):
        total += (v * 91 + idx) % 101
    return total / max(len(values), 1)
